type Company {
  name: String!
  catchPhrase: String!
  bs: String!
}

type Geo {
  lat: Float!
  lng: Float!
}

type ClientAddress {
  street: String!
  suite: String!
  city: String!
  zipcode: String!
  geo: Geo!
}

type ClientUser {
  id: ID!
  name: String!
  username: String!
  email: String!
  address: ClientAddress!
}

type Query {
  users: [ClientUser!]!
}
